# Place a copy of this file in the same directory and rename it to config.yaml

database:
  uri: 'mongodb://localhost:27017'
  key: './path/to/key.pem (optional)'

discord:
  clientId: '123456'
  clientSecret: 'A secret'
  redirectUri: 'http://localhost:4200/code'
  discordApiUrl: 'https://discord.com/api/v10'

auth:
  jwtSecret: 'Another secret'
  jwtLifetime: 3600
