name: Build and Deploy to Netlify
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      # - main
jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Common
        run: npm run build -w clan.events.common

      - name: Build Client
        run: npm run build -w clan.events.Client

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./clan.events.client/dist/clan.events.client"
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ONty4ZuxK0QPtVXRQmlNsE7MLaN6phCBdOnoV1q1icI
          NETLIFY_SITE_ID: d5076484-7014-44bd-b159-0dbecad92700
        timeout-minutes: 1
